name: Summarization

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          

      - name: Run the script
        run: python src/summarization.py
        env: # Убедитесь, что все необходимые переменные окружения перечислены здесь
          endpoint_300: ${{ secrets.endpoint_300 }}
          token_300: ${{ secrets.token_300 }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          rss_300_file_name: ${{ secrets.rss_300_file_name }}
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          logo_url: ${{ secrets.logo_url }}
          rss_url: ${{ secrets.rss_url }}
          RPS: ${{ secrets.RPS }}
          RSS_LINKS: ${{ secrets.RSS_LINKS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}  

